server:
  port: 8080

spring:
  config:
    import: env.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        security: trace